// V3 seed data — all simulated, no real API, ERP, or Teams connections

export const MANAGER = {
  name: 'Sandra Arceneaux',
  role: 'Branch Service Manager',
  branch: 'Gulf Coast Region',
  avatar: 'SA',
}

export const LOGGED_IN_TECH = {
  name: 'Jake Thibodaux',
  role: 'Field Technician',
  branch: 'Gulf Coast Region',
  avatar: 'JT',
  phone: '+1 (504) 555-0183',
  email: 'j.thibodaux@hcsg.com',
}

export const EQUIPMENT_CATALOG = [
  {
    id: 'eq-001',
    model: 'Shaw-Box Series B800SS',
    serial: 'SB800-2T-4471',
    type: 'Wire Rope Hoist',
    category: 'hoist',
    capacity: '2 Ton',
    customer: 'Westlake Chemical',
    site: 'Sulphur, LA',
    manualRef: 'Shaw-Box 800 Series Service Manual, Rev. 4',
  },
  {
    id: 'eq-002',
    model: 'Yale CPA Series Overhead Crane',
    serial: 'YC-CPA-10T-8823',
    type: 'Overhead Bridge Crane',
    category: 'crane',
    capacity: '10 Ton',
    customer: 'Huntsman Petrochemicals',
    site: 'Port Neches, TX',
    manualRef: 'Yale CPA Series Installation & Maintenance Manual',
  },
  {
    id: 'eq-003',
    model: 'Dover Hydraulic Elevator',
    serial: 'DV-HYD-6601',
    type: 'Hydraulic Passenger Elevator',
    category: 'elevator',
    capacity: '2500 lb',
    customer: 'Entergy Louisiana',
    site: 'New Orleans, LA',
    manualRef: 'Dover Hydraulic Series Maintenance Manual, Rev. 2',
  },
  {
    id: 'eq-004',
    model: 'Acco Coffing JLC-2T Hoist',
    serial: 'JLC-2T-3390',
    type: 'Chain Hoist',
    category: 'hoist',
    capacity: '2 Ton',
    customer: 'BASF Corporation',
    site: 'Geismar, LA',
    manualRef: 'Coffing JLC Series Maintenance Manual',
  },
]

// Hero Script A — Jake resolves alone (scan QR → confirm → chat → resolved)
export const SESSION_A = {
  id: 'session-a',
  techId: 'jake',
  equipment: EQUIPMENT_CATALOG[0],
  identifyMethod: 'qr',
  startedAt: 'Today, 9:14 AM',
  status: 'resolved',
  messages: [
    {
      id: 'm1',
      role: 'user',
      text: "It won't lift past halfway. The hoist makes a humming sound and just stops.",
      time: '9:15 AM',
      isVoice: true,
    },
    {
      id: 'm2',
      role: 'ai',
      text: "Based on your description — stopping mid-lift with a humming sound — the most likely cause is **thermal overload cutout** triggered by the motor running hot, or a **worn motor brake** dragging under load.\n\nStart by letting the hoist cool for 10 minutes, then retry a light lift. If it trips again immediately, the thermal protector may be faulty. If it lifts light loads fine but stops under full load, the brake is the primary suspect.",
      time: '9:15 AM',
      refs: [
        { label: 'Shaw-Box 800 Manual, p.18', page: 18 },
        { label: 'Section 6-3: Motor Protection', page: 18 },
      ],
      workOrderCitation: null,
    },
    {
      id: 'm3',
      role: 'user',
      text: 'Tried the light load — it lifts fine. Under full load it stops at about halfway and hums.',
      time: '9:22 AM',
      isVoice: false,
    },
    {
      id: 'm4',
      role: 'ai',
      text: "That confirms it — **the motor brake is dragging under load.** The brake isn't fully releasing, so the motor fights both the load and the brake. This is a common failure mode when the brake air gap exceeds 0.200\".\n\nNext step: **LOCKOUT/TAGOUT** the unit, remove the brake cover, and measure the air gap. Factory spec is 0.100\". If you're at 0.200\" or more, adjust the gap and replace the friction disc if worn below 3/32\".",
      time: '9:22 AM',
      refs: [
        { label: 'Shaw-Box 800 Manual, p.23', page: 23 },
        { label: 'Section 7-2: Motor Brake Adjustment', page: 23 },
      ],
      workOrderCitation: {
        text: 'Seen on 3 prior jobs for this model in Gulf Coast fleet',
        resolution: 'Friction disc replaced (Part No. 800-5005), gap reset to 0.100". Zero drift confirmed on test run.',
        techName: 'R. Fontenot',
        date: 'Jul 2024',
      },
    },
    {
      id: 'm5',
      role: 'user',
      text: 'Measured the gap — sitting at 0.215". Replacing the friction disc now.',
      time: '9:41 AM',
      isVoice: false,
    },
    {
      id: 'm6',
      role: 'ai',
      text: "Good catch — that gap is well past the service limit. After replacing the disc, torque the brake cover bolts to spec and do a **no-load lift first**, then full rated load. Confirm zero drift at rest before clearing the unit for service.",
      time: '9:41 AM',
      refs: [
        { label: 'Shaw-Box 800 Manual, p.24', page: 24 },
        { label: 'Section 7-2: Torque Specifications', page: 24 },
      ],
      workOrderCitation: null,
    },
    {
      id: 'm7',
      role: 'user',
      text: 'Disc replaced, gap set to 0.100". Full load test — lifts clean, zero drift. All good.',
      time: '10:03 AM',
      isVoice: false,
    },
    {
      id: 'm8',
      role: 'ai',
      text: "Resolved. Document the gap measurement (0.215\" found, 0.100\" set) and part number used (800-5005) in your job notes. Good work.",
      time: '10:03 AM',
      refs: [],
      workOrderCitation: null,
    },
  ],
}

// Hero Script B — Ryan stuck, manager escalates (manager opens detail → reads thread → Messages in Teams)
export const SESSION_B = {
  id: 'session-b',
  techId: 'ryan',
  equipment: EQUIPMENT_CATALOG[1],
  identifyMethod: 'text',
  startedAt: 'Today, 11:02 AM',
  status: 'active',
  messages: [
    {
      id: 'rb1',
      role: 'user',
      text: "Bridge crane won't travel east direction. West travel works fine.",
      time: '11:03 AM',
      isVoice: false,
    },
    {
      id: 'rb2',
      role: 'ai',
      text: "One-directional travel failure usually points to **a faulty contactor, limit switch, or motor in the east drive circuit.** Since west travel is fine, the main power and drive inverter are likely OK.\n\nCheck the east travel contactor first — look for burnt contacts or coil failure. Then verify the east end-of-travel limit switch isn't stuck open.",
      time: '11:03 AM',
      refs: [
        { label: 'Yale CPA Manual, p.44', page: 44 },
        { label: 'Section 8-1: Bridge Travel Circuit', page: 44 },
      ],
      workOrderCitation: null,
    },
    {
      id: 'rb3',
      role: 'user',
      text: 'Checked east contactor — looks fine, no burn marks. Limit switch also OK, spring is good.',
      time: '11:18 AM',
      isVoice: false,
    },
    {
      id: 'rb4',
      role: 'ai',
      text: "With the contactor and limit switch cleared, next suspects are the **bridge travel motor on the east end** or **pendant wiring for the east direction button.**\n\nTest the pendant: use a multimeter to check continuity on the east direction circuit when the button is pressed. If signal reaches the contactor coil but the crane still won't move, the east drive motor may have an open winding.",
      time: '11:18 AM',
      refs: [
        { label: 'Yale CPA Manual, p.51', page: 51 },
        { label: 'Section 8-4: Motor Winding Test', page: 51 },
      ],
      workOrderCitation: null,
    },
    {
      id: 'rb5',
      role: 'user',
      text: "Pendant is sending signal — confirmed with multimeter. Motor gets power but doesn't turn. I'm stuck.",
      time: '11:34 AM',
      isVoice: false,
    },
    {
      id: 'rb6',
      role: 'ai',
      text: "Motor receives power but doesn't rotate — that typically means a **seized motor bearing, open winding, or shorted rotor.** On a 10-ton crane this is beyond a field adjustment — the east bridge motor likely needs to be pulled and sent for testing or replaced.\n\nRecommend escalating to your branch manager before pulling the motor. The customer will need a crane out-of-service notice.",
      time: '11:34 AM',
      refs: [
        { label: 'Yale CPA Manual, p.53', page: 53 },
        { label: 'Section 8-5: Motor Replacement', page: 53 },
      ],
      workOrderCitation: {
        text: 'Similar case on Yale CPA 10T at Huntsman (2023)',
        resolution: 'East bridge motor replaced — seized bearing confirmed on teardown. Unit back in service in 4 hours.',
        techName: 'M. Broussard',
        date: 'Nov 2023',
      },
    },
  ],
}

export const TECHNICIANS = [
  {
    id: 'ryan',
    name: 'Ryan Fontenot',
    avatar: 'RF',
    role: 'Senior Technician',
    phone: '+1 (337) 555-0142',
    teamsHandle: 'ryan.fontenot',
    equipment: 'Yale CPA Series — 10T Bridge Crane',
    equipmentShort: 'Yale CPA 10T',
    lastQuery: "Motor gets power but doesn't turn. I'm stuck.",
    recency: 'now',
    recencyLabel: 'Active now',
    sessionRef: SESSION_B,
  },
  {
    id: 'marcus',
    name: 'Marcus Broussard',
    avatar: 'MB',
    role: 'Field Technician',
    phone: '+1 (504) 555-0219',
    teamsHandle: 'marcus.broussard',
    equipment: 'Dover Hydraulic Elevator',
    equipmentShort: 'Dover Hydraulic',
    lastQuery: 'Elevator slow to respond on call — floor 3 only.',
    recency: '2h',
    recencyLabel: '2h ago',
    sessionRef: null,
  },
  {
    id: 'jake',
    name: 'Jake Thibodaux',
    avatar: 'JT',
    role: 'Field Technician — Fast Track',
    phone: '+1 (504) 555-0183',
    teamsHandle: 'jake.thibodaux',
    equipment: 'Shaw-Box B800SS Hoist',
    equipmentShort: 'Shaw-Box B800SS',
    lastQuery: "Disc replaced, gap set to 0.100\". Zero drift. All good.",
    recency: '1h',
    recencyLabel: '1h ago',
    sessionRef: SESSION_A,
  },
  {
    id: 'derrick',
    name: 'Derrick Landry',
    avatar: 'DL',
    role: 'Field Technician',
    phone: '+1 (985) 555-0377',
    teamsHandle: 'derrick.landry',
    equipment: 'Acco Coffing JLC Hoist',
    equipmentShort: 'Coffing JLC',
    lastQuery: "What's the brake spring preload for JLC-2T?",
    recency: '1d',
    recencyLabel: 'Yesterday',
    sessionRef: null,
  },
  {
    id: 'trish',
    name: 'Trish Hebert',
    avatar: 'TH',
    role: 'Field Technician',
    phone: '+1 (337) 555-0081',
    teamsHandle: 'trish.hebert',
    equipment: 'Overhead Door HD Series',
    equipmentShort: 'OH Door HD',
    lastQuery: 'Spring tension adjustment for 14ft door.',
    recency: '1d',
    recencyLabel: 'Yesterday',
    sessionRef: null,
  },
  {
    id: 'carl',
    name: 'Carl Tureaud',
    avatar: 'CT',
    role: 'Senior Technician',
    phone: '+1 (504) 555-0295',
    teamsHandle: 'carl.tureaud',
    equipment: 'Shaw-Box Series 700',
    equipmentShort: 'Shaw-Box 700',
    lastQuery: 'Upper travel limit switch replacement.',
    recency: '2d',
    recencyLabel: '2d ago',
    sessionRef: null,
  },
  {
    id: 'pete',
    name: 'Pete Melancon',
    avatar: 'PM',
    role: 'Field Technician',
    phone: '+1 (985) 555-0449',
    teamsHandle: 'pete.melancon',
    equipment: 'Otis Gen2 Elevator',
    equipmentShort: 'Otis Gen2',
    lastQuery: 'Door zone sensor alignment procedure.',
    recency: '5d',
    recencyLabel: '5d ago',
    sessionRef: null,
  },
  {
    id: 'lisa',
    name: 'Lisa Guidry',
    avatar: 'LG',
    role: 'Field Technician',
    phone: '+1 (337) 555-0562',
    teamsHandle: 'lisa.guidry',
    equipment: 'Yale MR Series Monorail',
    equipmentShort: 'Yale MR Monorail',
    lastQuery: 'Trolley wheel flange wear — service limits?',
    recency: '5d',
    recencyLabel: '5d ago',
    sessionRef: null,
  },
]

export const LIVE_QUERIES = [
  {
    id: 'lq1',
    techId: 'ryan',
    techName: 'Ryan Fontenot',
    techAvatar: 'RF',
    equipment: 'Yale CPA 10T Bridge Crane',
    query: "Motor gets power but doesn't turn. I'm stuck.",
    time: '11:34 AM',
    turns: 5,
    status: 'active',
  },
  {
    id: 'lq2',
    techId: 'marcus',
    techName: 'Marcus Broussard',
    techAvatar: 'MB',
    equipment: 'Dover Hydraulic Elevator',
    query: 'Elevator slow to respond on call — floor 3 only.',
    time: '9:47 AM',
    turns: 3,
    status: 'idle',
  },
  {
    id: 'lq3',
    techId: 'jake',
    techName: 'Jake Thibodaux',
    techAvatar: 'JT',
    equipment: 'Shaw-Box B800SS Hoist',
    query: 'Resolved — brake friction disc replaced, gap set to 0.100".',
    time: '10:03 AM',
    turns: 7,
    status: 'resolved',
  },
]

export const TOP_QUERIES = [
  { rank: 1, query: 'Motor brake air gap adjustment procedure', count: 14, equipment: 'Shaw-Box 800 Series' },
  { rank: 2, query: "Hoist won't lift at full load", count: 11, equipment: 'Multiple' },
  { rank: 3, query: 'Bridge travel — one direction only', count: 8, equipment: 'Overhead Crane' },
  { rank: 4, query: 'Limit switch replacement — upper travel', count: 7, equipment: 'Multiple' },
  { rank: 5, query: 'Load brake friction washer service limits', count: 6, equipment: 'Shaw-Box Series' },
  { rank: 6, query: 'Elevator door zone sensor alignment', count: 5, equipment: 'Otis / Dover' },
]

export const DOCUMENTS = [
  {
    id: 'doc-1',
    title: 'Shaw-Box 800 Series Service Manual',
    type: 'Service Manual',
    equipment: 'Shaw-Box Series 800 Hoist',
    revision: 'Rev. 4',
    pages: 68,
    uploadedAt: 'May 12, 2025',
    status: 'indexed',
  },
  {
    id: 'doc-2',
    title: 'Yale CPA Series Installation & Maintenance Manual',
    type: 'Maintenance Manual',
    equipment: 'Yale CPA Overhead Crane',
    revision: 'Rev. 2',
    pages: 112,
    uploadedAt: 'Apr 3, 2025',
    status: 'indexed',
  },
  {
    id: 'doc-3',
    title: 'Dover Hydraulic Series Maintenance Manual',
    type: 'Maintenance Manual',
    equipment: 'Dover Hydraulic Elevator',
    revision: 'Rev. 2',
    pages: 89,
    uploadedAt: 'Mar 18, 2025',
    status: 'indexed',
  },
]

export const PAST_SESSIONS = [
  {
    id: 'ps-1',
    equipment: 'Shaw-Box B800SS Hoist',
    query: "Won't lift past halfway — humming sound",
    date: 'Today',
    status: 'resolved',
    turns: 7,
  },
  {
    id: 'ps-2',
    equipment: 'Coffing JLC-2T Hoist',
    query: 'Brake spring preload procedure',
    date: 'Yesterday',
    status: 'resolved',
    turns: 4,
  },
  {
    id: 'ps-3',
    equipment: 'Shaw-Box Series 800',
    query: 'Wire rope inspection — retirement criteria',
    date: 'Jun 2',
    status: 'resolved',
    turns: 3,
  },
]

export const SUGGESTED_PROMPTS = [
  "Common faults",
  "Won't lift",
  "Strange noise",
  "Error codes",
]

// AI responses for open-ended chat (cycles through scripted replies)
export const AI_RESPONSES = SESSION_A.messages.filter(m => m.role === 'ai')
